- .github/workflows/build_docker.yml
- build_versions.json
needs: https://github.com/voxpupuli/gha-build-and-publish-a-container/pull/25
replaces: #18 
fixes: https://github.com/voxpupuli/crafty/issues/5, #17
> Add matrix setup to build several versions in parallel specified in a json file

- .github/workflows/build_docker.yml
fixes: https://github.com/voxpupuli/crafty/issues/6
> Update build_arch to include linux/arm64

- .github/workflows/build_docker.yml
fixes: https://github.com/voxpupuli/crafty/issues/7
> also push to dockerhub

- README.md
- use container from github
- a contributing link
fixes: #20
> Update Readme to use containers from github and add contributing link

- README.md
- puppetserver/Dockerfile
- puppetserver/docker-entrypoint.d/83-environment-cache.sh
- puppetserver/docker-entrypoint.d/84-enable_graphite.sh
- puppetserver/metrics.conf.tmpl
- manage environment timeout
- manage graphite exporter
> Add Metrics and Environment cache timeout

- puppetserver/docker-entrypoint.d/88-enable-cache-delete-api.sh
> make setting of env api endpoint idempotent

- CHANGELOG.md
> Release-v1.1.2

- .github/workflows/build_docker.yml
> build latest version for each puppet version

- puppetserver/Dockerfile
> Add Ruby 3.0 to Dockerfile to get r10k 4.x running

- README.md
- puppetserver/Dockerfile
- puppetserver/docker-entrypoint.d/50-set-certname.sh
- puppetserver/docker-entrypoint.d/99-log-config.sh
- split PUPPETSERVER_HOSTNAME into CERTNAME
> Add support for certname parameter

- .github/workflows/labeler.yml
- .github/workflows/release.yml
- CHANGELOG.md
micro release to test if the workflows are working
> Release v1.4.1

- puppetserver/docker-entrypoint.d/20-use-templates-initially.sh
- puppetserver/docker-entrypoint.d/30-set-permissions.sh
- puppetserver/docker-entrypoint.d/40-update-puppetdb-conf.sh
- puppetserver/docker-entrypoint.d/50-set-certname.sh
- puppetserver/docker-entrypoint.d/55-set-masterport.sh
- puppetserver/docker-entrypoint.d/56-set-environmentpath.sh
- puppetserver/docker-entrypoint.d/57-set-hiera_config.sh
- puppetserver/docker-entrypoint.d/60-setup-autosign.sh
- puppetserver/docker-entrypoint.d/70-set-dns-alt-names.sh
- puppetserver/docker-entrypoint.d/83-environment-cache.sh
- puppetserver/docker-entrypoint.d/84-enable_graphite.sh
- puppetserver/docker-entrypoint.d/85-setup-storeconfigs.sh
- puppetserver/docker-entrypoint.d/88-enable-cache-delete-api.sh
- puppetserver/docker-entrypoint.d/89-csr_attributes.rb
- puppetserver/docker-entrypoint.d/89-csr_attributes.sh
- puppetserver/docker-entrypoint.d/90-ca.sh
- puppetserver/docker-entrypoint.d/99-log-config.sh
> add set -e to all scripts.

- README.md
Add compose example on how to handle the CA.
Relates to: #88
> docu: update how to handle ca

- .github/dependabot.yml
- .github/release.yml
- .github/workflows/release.yml
- .gitignore
- Gemfile
> modulesync 

- .github/workflows/build_docker.yml
Fixes: https://github.com/voxpupuli/crafty/issues/61
> Use short container names

- README.md
https://github.com/voxpupuli/container-puppetserver/blob/c31119fe37def9a44f03c0d36b010bedaa20369a/puppetserver/Dockerfile#L23
> Fix default argument for PUPPETSERVER_JAVA_ARGS in README

- .github/workflows/ci.yaml
- puppetserver/Dockerfile
- so we only have to approve them
- enables the github feature auto-merge
- only add this if tests pass
>     feat: enable the auto-merge feature on dependabot prs

- puppetserver/docker-entrypoint.sh
Ensure the entrypoint script does not fail on directories existing but not containing any .sh files
> Ensure the entrypoint script does not fail.

- puppetserver/Dockerfile
> feat: streamline Dockerfile

- puppetserver/docker-entrypoint.d/90-ca.sh
ca ttl is only needed if we are ca
> fix ca ttl setting.
